<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" tests="6" skipped="0" failures="0" errors="0" timestamp="2020-06-22T06:04:25" hostname="aiguoxindeMacBook-Pro.local" time="0.309">
  <properties/>
  <testcase name="clearFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.169"/>
  <testcase name="getFailPutExceptionFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.025"/>
  <testcase name="evictFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.036"/>
  <testcase name="putFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.029"/>
  <testcase name="getFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.026"/>
  <testcase name="getPutNewElementFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.024"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
